"""empty message

Revision ID: aca8957fc09d
Revises: 
Create Date: 2021-02-26 16:48:04.476218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca8957fc09d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('chaid', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('height', sa.String(length=100), nullable=True),
    sa.Column('mass', sa.String(length=100), nullable=True),
    sa.Column('hair_color', sa.String(length=100), nullable=True),
    sa.Column('eye_color', sa.String(length=100), nullable=True),
    sa.Column('skin_color', sa.String(length=100), nullable=True),
    sa.Column('birth_year', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('chaid')
    )
    op.create_table('planets',
    sa.Column('plaid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.String(length=100), nullable=True),
    sa.Column('rotation_period', sa.String(length=100), nullable=True),
    sa.Column('orbital_period', sa.String(length=100), nullable=True),
    sa.Column('gravity', sa.String(length=100), nullable=True),
    sa.Column('population', sa.String(length=100), nullable=True),
    sa.Column('Climate', sa.String(length=100), nullable=True),
    sa.Column('terrain', sa.String(length=100), nullable=True),
    sa.Column('surface_water', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('plaid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('favorites',
    sa.Column('favid', sa.Integer(), nullable=False),
    sa.Column('user_userid', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('favid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('planets')
    op.drop_table('character')
    # ### end Alembic commands ###
